services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: docker_pass
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
  session:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./docker/session/redis:/data
